name: Development

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch
      uses: actions/checkout@v3
      
    - name: Init
      run: rustup component add rustfmt clippy

    - name: Check
      run: cargo check

    - name: Test
      run: cargo test
  
    - name: Format
      run: cargo fmt --all -- --check
    
    - name: Lint
      run: cargo clippy -- -Dwarnings